### ISSUE TITLE
Searching causes RO error

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-client#126]
Opening search with `F3` causes this error on both the client and server but since its related to searching I feel like it fits here more.

```
Error: Mountpoint 'osjs' is read-only
    at createError (/home/ross/emberliteOS/OS.js/node_modules/@osjs/server/src/utils/vfs.js:150:13)
    at /home/ross/emberliteOS/OS.js/node_modules/@osjs/server/src/utils/vfs.js:133:33
    at /home/ross/emberliteOS/OS.js/node_modules/@osjs/server/src/vfs.js:154:70
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 403
}
```

**Comment by andersevenrud** [comment]
Moving to @osjs/server
